name: Create User Database

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (apply/destroy)'
        required: true
        type: choice
        options:
          - apply
          - destroy
      workspace:
        description: 'Terraform workspace to use'
        required: true
        type: choice
        options:
          - ancl11
          - stma7
          # Add new workspaces here

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.4.6'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.DEV_AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: eu-west-2

      - name: Terraform Init
        working-directory: infrastructure/stacks/user-database
        env:
          TF_WORKSPACE: ${{ github.event.inputs.workspace }}
        run: terraform init

      - name: Check current workspace
        working-directory: infrastructure/stacks/user-database
        run: terraform workspace select ${{ github.event.inputs.workspace }}

      - name: Terraform ${{ github.event.inputs.action }}
        working-directory: infrastructure/stacks/user-database
        env:
          TF_VAR_db_name: ${{ github.event.inputs.workspace }}
        run: terraform ${{ github.event.inputs.action }} -auto-approve -var-file="../../environments/01-DEV/main.tfvars"

      - name: Cleanup
        if: always()
        working-directory: infrastructure/stacks/user-database
        run: terraform workspace select default

